name: Build rsvg-convert on Windows (MSYS2)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      RSVG_TAG: 2.60.0   # 指定要编译的 librsvg 版本

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone librsvg source
        shell: pwsh
        run: |
          git clone --depth 1 --branch $env:RSVG_TAG `
            https://gitlab.gnome.org/GNOME/librsvg.git librsvg

      - name: Setup MSYS2 and install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: |
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-pango
            mingw-w64-x86_64-librsvg
            mingw-w64-x86_64-rust
            mingw-w64-x86_64-rust-src

      - name: Install cargo-cbuild
        shell: msys2 {msystem=mingw64}
        run: |
          cargo install cargo-c --locked

      - name: Build librsvg with Meson & Ninja
        shell: msys2 {msystem=mingw64}
        run: |
          cd librsvg
          mkdir -p build && cd build

          # 生成 Meson cross-file，显式声明需要的工具
          cat > crossfile.ini << 'EOF'
          [binaries]
          c = 'x86_64-w64-mingw32-gcc'
          cpp = 'x86_64-w64-mingw32-g++'
          ar = 'x86_64-w64-mingw32-ar'
          strip = 'x86_64-w64-mingw32-strip'
          pkg-config = 'pkg-config'
          cargo-cbuild = 'cargo-cbuild'
          
          [properties]
          needs_exe_wrapper = true
          
          [host_machine]
          system = 'windows'
          cpu_family = 'x86_64'
          cpu = 'x86_64'
          endian = 'little'
          EOF

          # 使用绝对路径作为安装前缀
          PREFIX=$(pwd)/install

          meson setup \
            --cross-file crossfile.ini \
            --prefix "$PREFIX" \
            --default-library static \
            -Dbuildtype=release \
            -Db_lto=true \
            -Dintrospection=disabled \
            ..

          ninja
          ninja install

      - name: Upload rsvg-convert.exe
        uses: actions/upload-artifact@v4
        with:
          name: rsvg-convert-windows
          path: librsvg/build/install/bin/rsvg-convert.exe
