name: Build rsvg-convert on Windows (MSYS2)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      RSVG_TAG: 2.60.0   # 要编译的 librsvg 版本

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone librsvg source
        shell: pwsh
        run: |
          git clone --depth 1 --branch $env:RSVG_TAG `
            https://gitlab.gnome.org/GNOME/librsvg.git librsvg

      - name: Setup MSYS2 and install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            git
            p7zip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-rust
            mingw-w64-x86_64-cargo-c
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-pango
            mingw-w64-x86_64-gdk-pixbuf2
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-expat
            mingw-w64-x86_64-bzip2
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-brotli
            mingw-w64-x86_64-fontconfig
            mingw-w64-x86_64-pixman
            mingw-w64-x86_64-gcc-libs

      - name: Build librsvg with Meson & Ninja
        shell: msys2 {0}
        run: |
          cd librsvg
          mkdir build && cd build

          # 使用绝对路径作为 prefix
          meson setup build \
            --prefix $(pwd)/install \
            --default-library shared \
            -Dbuildtype=release \
            -Db_lto=false \
            -Dintrospection=disabled \
            -Dpixbuf-loader=disabled \
            -Dtests=false \
            ..

          ninja -C build
          ninja -C build install

          # 复制所有必要的 DLL 到 bin 目录
          cd install/bin
          ldd rsvg-convert.exe | grep -i mingw | awk '{print $3}' | xargs -I{} cp {} .

      - name: Upload rsvg-convert.exe and dependencies
        uses: actions/upload-artifact@v4
        with:
          name: rsvg-convert-windows
          path: librsvg/build/install/bin/*
