name: Build rsvg-convert on Windows (MSYS2)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      RSVG_TAG: 2.60.0    # 要编译的 librsvg 版本

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone librsvg source
        shell: pwsh
        run: |
          git clone --depth 1 --branch $env:RSVG_TAG `
            https://gitlab.gnome.org/GNOME/librsvg.git librsvg

      - name: Setup MSYS2 and install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: |
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-pango
            mingw-w64-x86_64-librsvg
            mingw-w64-x86_64-rust
            mingw-w64-x86_64-rust-src

      - name: Build librsvg with Meson & Ninja
        shell: msys2 {0}
        run: |
          cd librsvg
          mkdir -p build && cd build

          # 使用绝对路径作为前缀
          PREFIX=$(pwd)/install

          # 正确的 meson 语法：先所有选项，再把 .. 当成源码目录
          meson setup \
            --prefix "$PREFIX" \
            --default-library static \
            -Dbuildtype=release \
            -Db_lto=true \
            -Dintrospection=disabled \
            ..

          ninja
          ninja install

      - name: Upload rsvg-convert.exe
        uses: actions/upload-artifact@v4
        with:
          name: rsvg-convert-windows
          path: librsvg/build/install/bin/rsvg-convert.exe
