name: Build rsvg-convert (static win64)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # 1. 安装 MSYS2 + 依赖
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-rust
            mingw-w64-x86_64-cargo-c
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-pango
            mingw-w64-x86_64-gdk-pixbuf2
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-expat
            mingw-w64-x86_64-bzip2
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-brotli
            mingw-w64-x86_64-fontconfig
            mingw-w64-x86_64-pixman

      # 2. 固定环境变量（静态 + CRT）
      - name: Prepare env
        shell: msys2 {0}
        run: |
          echo 'export PKG_CONFIG="pkg-config --static"' >> ~/.bashrc
          echo 'export RUSTFLAGS="-C target-feature=+crt-static -C link-arg=-static -C link-arg=-static-libgcc -C link-arg=-static-libstdc++"' >> ~/.bashrc

      # 3. 配置 Meson
      - name: Meson configure
        shell: msys2 {0}
        run: |
          source ~/.bashrc
          cd librsvg
          meson setup build \
            --wrap-mode=nodownload \
            --default-library=static \
            -Db_lto=true \
            -Dintrospection=disabled

      # 4. 编译
      - name: Ninja build
        shell: msys2 {0}
        run: |
          source ~/.bashrc
          cd librsvg/build
          ninja -j$(nproc)

      # 5. 打包产物
      - name: Collect artifact
        shell: msys2 {0}
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts
          cp rsvg_convert/rsvg-convert.exe $GITHUB_WORKSPACE/artifacts/

      - uses: actions/upload-artifact@v4
        with:
          name: rsvg-convert-static
          path: artifacts/rsvg-convert.exe
