name: Build rsvg-convert 2.60.0 (MXE + Rust, static Win64)

on:
  push:               # 任何 push 均触发；如需限定分支，可加 branches:
    # branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: mxe/mxe:latest     # 内含 x86_64-w64-mingw32.static 交叉链
      options: --user 0

    steps:
    # ─────────── 基础准备 ───────────
    - uses: actions/checkout@v4
      with: { fetch-depth: 1 }

    - name: Install Rust (with Windows-GNU target)
      run: |
        curl -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
        source "$HOME/.cargo/env"
        rustup target add x86_64-pc-windows-gnu
        rustc -V && cargo -V
        echo "CARGO_HOME=$HOME/.cargo" >> "$GITHUB_ENV"

    - name: Install build helpers
      run: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive \
          apt-get install -y meson ninja-build gettext

    # ─────────── 获取 librsvg 2.60.0 ───────────
    - name: Clone librsvg-2.60.0
      run: |
        git clone --depth 1 --branch 2.60.0 https://gitlab.gnome.org/GNOME/librsvg.git

    # ─────────── 生成 cross file ───────────
    - name: Generate Meson cross file
      working-directory: librsvg
      run: |
        cat > mxe-cross.txt <<'EOF'
        [binaries]
        c         = 'x86_64-w64-mingw32.static-gcc'
        cpp       = 'x86_64-w64-mingw32.static-g++'
        ar        = 'x86_64-w64-mingw32.static-ar'
        windres   = 'x86_64-w64-mingw32.static-windres'
        pkgconfig = 'x86_64-w64-mingw32.static-pkg-config'
        strip     = 'x86_64-w64-mingw32.static-strip'
        rust      = 'rustc'
        
        [properties]
        needs_exe_wrapper = true
        
        [built-in options]
        c_args        = ['-O2']
        cpp_args      = ['-O2']
        c_link_args   = ['-static']
        cpp_link_args = ['-static']
        default_library = 'static'
        EOF

    # ─────────── 配置 & 编译 ───────────
    - name: Configure with Meson
      working-directory: librsvg
      env:
        CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER: x86_64-w64-mingw32.static-gcc
        PKG_CONFIG_ALLOW_CROSS: "1"
        RUSTFLAGS: "-C target-feature=+crt-static -C linker=x86_64-w64-mingw32.static-gcc -C panic=abort"
      run: |
        meson setup build \
          --cross-file mxe-cross.txt \
          -Ddefault_library=static \
          -Dintrospection=disabled \
          -Dtests=false \
          -Db_lto=true

    - name: Build rsvg-convert
      working-directory: librsvg
      run: ninja -C build rsvg-convert

    # ─────────── Strip & 检查 ───────────
    - name: Strip and inspect binary
      working-directory: librsvg
      run: |
        x86_64-w64-mingw32.static-strip build/rsvg-convert.exe
        file build/rsvg-convert.exe
        du -h build/rsvg-convert.exe

    # ─────────── 上传产物 ───────────
    - uses: actions/upload-artifact@v4
      with:
        name: rsvg-convert-2.60.0-win64-static
        path: librsvg/build/rsvg-convert.exe
