name: Build Windows static rsvg-convert (Meson)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MinGW and Meson
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          meson \
          ninja-build \
          mingw-w64 \
          upx-ucl \
          pkg-config \
          python3-pip
        
        # 安装交叉编译的依赖工具链
        pip install crossenv

    - name: Setup cross-compilation
      shell: bash
      run: |
        export HOST=x86_64-w64-mingw32
        export CC=${HOST}-gcc
        export CXX=${HOST}-g++
        export AR=${HOST}-ar
        export PKG_CONFIG=${HOST}-pkg-config
        export PKG_CONFIG_PATH=/usr/${HOST}/lib/pkgconfig

        echo "HOST=${HOST}" >> $GITHUB_ENV
        echo "CC=${CC}" >> $GITHUB_ENV
        echo "CXX=${CXX}" >> $GITHUB_ENV
        echo "AR=${AR}" >> $GITHUB_ENV
        echo "PKG_CONFIG=${PKG_CONFIG}" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}" >> $GITHUB_ENV

    - name: Build dependencies (static)
      run: |
        # 示例：静态编译 libxml2（其他依赖类似）
        curl -L https://download.gnome.org/sources/libxml2/2.12/libxml2-2.12.5.tar.xz | tar xJ
        cd libxml2-2.12.5
        ./configure --host=${{ env.HOST }} --enable-static --disable-shared --without-python \
          CFLAGS="-Os" LDFLAGS="-static"
        make -j$(nproc)
        sudo make install
        cd ..

    - name: Build librsvg with Meson
      run: |
        # 下载 librsvg 2.60.0
        curl -L https://download.gnome.org/sources/librsvg/2.60/librsvg-2.60.0.tar.xz | tar xJ
        cd librsvg-2.60.0

        # 配置 Meson 选项（静态链接）
        meson setup build \
          --cross-file scripts/cross-mingw64.txt \
          --prefix=/usr/${{ env.HOST }} \
          --buildtype=release \
          --default-library=static \
          -Dintrospection=disabled \
          -Ddocs=false \
          -Dtests=false \
          -Dgtk_doc=false \
          -Dgdk_pixbuf=disabled \
          -Drsvg_bin=true

        # 编译并安装
        meson compile -C build
        meson install -C build

        # 提取二进制文件
        mkdir -p ../artifacts
        cp /usr/${{ env.HOST }}/bin/rsvg-convert.exe ../artifacts/
        ${{ env.HOST }}-strip ../artifacts/rsvg-convert.exe -o ../artifacts/rsvg-convert-stripped.exe
        upx --best --lzma ../artifacts/rsvg-convert-stripped.exe -o ../artifacts/rsvg-convert-upx.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rsvg-convert-windows
        path: artifacts/

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/rsvg-convert-upx.exe
        body: |
          Static Windows build of rsvg-convert 2.60.0 (Meson)
          - Built with MinGW-w64
          - All dependencies statically linked
          - Compressed with UPX