name: Build Static rsvg-convert on Windows

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build rsvg-convert
        shell: pwsh
        run: |
          .\win-static.ps1

      - name: Upload install folder
        uses: actions/upload-artifact@v4
        with:
          name: librsvg-windows
          path: rsvg.ci.bin/**
