name: Build Static rsvg-convert on Windows

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build rsvg-convert
        shell: pwsh
        run: |
          .\win-static.ps1

      - name: Upload install folder
        uses: actions/upload-artifact@v4
        with:
          name: librsvg-windows
          path: rsvg.ci.bin/**

      - name: Compress rsvg-convert.exe
        shell: pwsh
        run: |
          Compress-Archive `
            -Path rsvg.ci.bin/bin/rsvg-convert.exe `
            -DestinationPath rsvg.ci.bin/bin/win-static-x64.zip

      - name: Extract rsvg-convert version
        id: get_rc_version
        shell: pwsh
        run: |
          $output = & .\rsvg.ci.bin\bin\rsvg-convert.exe
          # get version number
          if ($output -match 'version\s+(\d+\.\d+\.\d+)') {
            $ver = $Matches[1]
            Write-Host "Parsed version: $ver"
            # set rc_version
            "rc_version=$ver" | Out-File -Encoding utf8 -NoNewline $env:GITHUB_OUTPUT
          } else {
            Write-Error "Unable to parse version from: $output"
            exit 1
          }

      - name: Create & Publish Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: rsvg-convert-${{ steps.get_rc_version.outputs.rc_version }} build ${{ github.ref_name }}
          artifacts: rsvg.ci.bin/bin/win-static-x64.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
