name: Build Static rsvg-convert on Windows

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Colorful output via ANSI
        shell: pwsh
        run: |
          # 定义一些常用颜色
          $red    = "`e[31m"
          $green  = "`e[32m"
          $yellow = "`e[33m"
          $reset  = "`e[0m"

          Write-Host "${green}✅ Success!${reset}"
          Write-Host "${yellow}⚠️ Warning…${reset}"
          Write-Host "${red}❌ Error!${reset}"

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build rsvg-convert
        shell: pwsh
        run: |
          .\win-static.ps1

      - name: Upload install folder
        uses: actions/upload-artifact@v4
        with:
          name: librsvg-windows
          path: rsvg.ci.bin/**
