name: Build rsvg-convert 2.60.0 (MXE + Rust, static Win64)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 1 }

    # ───── ① 添加 MXE 仓库（focal）并导入两把 GPG 密钥 ─────
    - name: Add MXE APT repo (focal) + import GPG keys
      run: |
        sudo mkdir -p /usr/share/keyrings

        # 下载并去装甲，两把钥匙依次追加到同一 keyring
        for KEY in 86B72ED9 33A3A276; do
          curl -fsSL "https://pkg.mxe.cc/repos/apt/conf/${KEY}.gpg" \
          | gpg --dearmor \
          | sudo tee -a /usr/share/keyrings/mxe-archive-keyring.gpg >/dev/null
        done

        # focal 仓库在 jammy 主机上使用没问题，因为包是交叉工具链
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/mxe-archive-keyring.gpg] \
             https://pkg.mxe.cc/repos/apt focal main" \
          | sudo tee /etc/apt/sources.list.d/mxe.list

        sudo apt-get update

    # ───── ② 安装 MXE 工具链 + 依赖 ─────
    - name: Install MXE toolchain & libs
      run: |
        sudo apt-get install -y \
          mxe-x86-64-w64-mingw32.static-gcc \
          mxe-x86-64-w64-mingw32.static-pkgconf \
          mxe-x86-64-w64-mingw32.static-glib2 \
          mxe-x86-64-w64-mingw32.static-cairo \
          mxe-x86-64-w64-mingw32.static-pango \
          mxe-x86-64-w64-mingw32.static-gdk-pixbuf \
          mxe-x86-64-w64-mingw32.static-harfbuzz \
          mxe-x86-64-w64-mingw32.static-fribidi \
          mxe-x86-64-w64-mingw32.static-libxml2 \
          mxe-x86-64-w64-mingw32.static-libcroco \
          mxe-x86-64-w64-mingw32.static-zlib

    # ───── ③ Rust + Meson + 编译 librsvg 2.60.0（步骤同前） ─────
    - name: Install Rust toolchain
      run: |
        curl -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
        source "$HOME/.cargo/env"
        rustup target add x86_64-pc-windows-gnu
        echo "CARGO_HOME=$HOME/.cargo" >> "$GITHUB_ENV"

    - name: Install Meson & Ninja
      run: sudo apt-get install -y meson ninja-build gettext

    - name: Checkout librsvg 2.60.0
      run: git clone --depth 1 --branch 2.60.0 https://gitlab.gnome.org/GNOME/librsvg.git

    - name: Create Meson cross file
      working-directory: librsvg
      run: |
        cat > mxe-cross.txt <<'EOF'
        [binaries]
        c         = 'x86_64-w64-mingw32.static-gcc'
        cpp       = 'x86_64-w64-mingw32.static-g++'
        ar        = 'x86_64-w64-mingw32.static-ar'
        windres   = 'x86_64-w64-mingw32.static-windres'
        pkgconfig = 'x86_64-w64-mingw32.static-pkg-config'
        strip     = 'x86_64-w64-mingw32.static-strip'
        rust      = 'rustc'
        
        [properties]
        needs_exe_wrapper = true
        
        [built-in options]
        c_args        = ['-O2']
        cpp_args      = ['-O2']
        c_link_args   = ['-static']
        cpp_link_args = ['-static']
        default_library = 'static'
        EOF

    - name: Meson configure
      working-directory: librsvg
      env:
        CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER: x86_64-w64-mingw32.static-gcc
        PKG_CONFIG_ALLOW_CROSS: "1"
        RUSTFLAGS: "-C target-feature=+crt-static -C linker=x86_64-w64-mingw32.static-gcc -C panic=abort"
      run: |
        meson setup build \
          --cross-file mxe-cross.txt \
          -Ddefault_library=static \
          -Dintrospection=disabled \
          -Dtests=false \
          -Db_lto=true

    - name: Build rsvg-convert
      working-directory: librsvg
      run: ninja -C build rsvg-convert

    - name: Strip binary
      working-directory: librsvg
      run: |
        x86_64-w64-mingw32.static-strip build/rsvg-convert.exe
        file build/rsvg-convert.exe
        du -h build/rsvg-convert.exe

    - uses: actions/upload-artifact@v4
      with:
        name: rsvg-convert-2.60.0-win64-static
        path: librsvg/build/rsvg-convert.exe
