name: Build rsvg-convert-2.60.0 (MXE binary + Rust static Win-x64)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04        # jammy runner 没问题，仓库用 focal

    steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 1 }

    # 1️⃣  添加 MXE 仓库（固定 focal）+ 两把 GPG 密钥
    - name: Add MXE repo & keys
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends gnupg dirmngr

        # 两把签名钥匙：86B72ED9（旧）+ 33A3A276（新）
        gpg --batch --keyserver hkp://keyserver.ubuntu.com:80 \
            --recv-keys 86B72ED9 33A3A276 || true

        sudo mkdir -p /usr/share/keyrings
        gpg --batch --export 86B72ED9 33A3A276 \
            | sudo tee /usr/share/keyrings/mxe.gpg >/dev/null

        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/mxe.gpg] \
             https://pkg.mxe.cc/repos/apt focal main" \
          | sudo tee /etc/apt/sources.list.d/mxe.list

        # 若第二把钥匙仍未同步，重试失败时降级 trusted=yes
        if ! sudo apt-get update -qq; then
          echo "::warning ::MXE repo signature check failed – falling back to trusted=yes"
          echo "deb [arch=amd64 trusted=yes] https://pkg.mxe.cc/repos/apt focal main" \
            | sudo tee /etc/apt/sources.list.d/mxe.list
          sudo apt-get update -qq
        fi

    # 2️⃣  安装交叉工具链 + librsvg 依赖（包名与 MXE 数据库一致）
    - name: Install MXE toolchain & libs
      run: |
        sudo apt-get install -y \
          mxe-x86-64-w64-mingw32.static-gcc \
          mxe-x86-64-w64-mingw32.static-pkgconf \
          mxe-x86-64-w64-mingw32.static-glib \
          mxe-x86-64-w64-mingw32.static-cairo \
          mxe-x86-64-w64-mingw32.static-pango \
          mxe-x86-64-w64-mingw32.static-gdk-pixbuf \
          mxe-x86-64-w64-mingw32.static-harfbuzz \
          mxe-x86-64-w64-mingw32.static-fribidi \
          mxe-x86-64-w64-mingw32.static-libxml2 \
          mxe-x86-64-w64-mingw32.static-libcroco \
          mxe-x86-64-w64-mingw32.static-zlib

    # 3️⃣  安装 Rust 并启用 Windows-GNU 目标
    - name: Install Rust toolchain
      run: |
        curl -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
        source "$HOME/.cargo/env"
        rustup target add x86_64-pc-windows-gnu
        echo "CARGO_HOME=$HOME/.cargo" >> "$GITHUB_ENV"

    # 4️⃣  Meson & Ninja
    - name: Install Meson & Ninja
      run: sudo apt-get install -y meson ninja-build gettext

    # 5️⃣  获取 librsvg-2.60.0 源码
    - name: Clone librsvg 2.60.0
      run: git clone --depth 1 --branch 2.60.0 https://gitlab.gnome.org/GNOME/librsvg.git

    # 6️⃣  生成 Meson cross-file
    - name: Create Meson cross file
      working-directory: librsvg
      run: |
        cat > mxe-cross.txt <<'EOF'
        [binaries]
        c         = 'x86_64-w64-mingw32.static-gcc'
        cpp       = 'x86_64-w64-mingw32.static-g++'
        ar        = 'x86_64-w64-mingw32.static-ar'
        windres   = 'x86_64-w64-mingw32.static-windres'
        pkgconfig = 'x86_64-w64-mingw32.static-pkg-config'
        strip     = 'x86_64-w64-mingw32.static-strip'
        rust      = 'rustc'
        
        [properties]
        needs_exe_wrapper = true
        
        [built-in options]
        c_args        = ['-O2']
        cpp_args      = ['-O2']
        c_link_args   = ['-static']
        cpp_link_args = ['-static']
        default_library = 'static'
        EOF

    # 7️⃣  配置 & 编译 rsvg-convert
    - name: Meson configure
      working-directory: librsvg
      env:
        CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER: x86_64-w64-mingw32.static-gcc
        PKG_CONFIG_ALLOW_CROSS: "1"
        RUSTFLAGS: "-C target-feature=+crt-static -C linker=x86_64-w64-mingw32.static-gcc -C panic=abort"
      run: |
        meson setup build \
          --cross-file mxe-cross.txt \
          -Ddefault_library=static \
          -Dintrospection=disabled \
          -Dtests=false \
          -Db_lto=true
    - name: Build rsvg-convert.exe
      working-directory: librsvg
      run: ninja -C build rsvg-convert

    # 8️⃣  strip & check
    - name: Strip + size check
      working-directory: librsvg
      run: |
        x86_64-w64-mingw32.static-strip build/rsvg-convert.exe
        file build/rsvg-convert.exe
        du -h build/rsvg-convert.exe

    # 9️⃣  发布 artifact
    - uses: actions/upload-artifact@v4
      with:
        name: rsvg-convert-2.60.0-win64-static
        path: librsvg/build/rsvg-convert.exe
