name: Cross-compile rsvg-convert for Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install native prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          mingw-w64 \
          meson \
          ninja-build \
          pkg-config

    - name: Setup MXE (x86_64-w64-mingw32, static)
      uses: stefanscherer/setup-mxe@v3
      with:
        mxe: x86_64-w64-mingw32.static
        packages: |
          glib
          libxml2
          cairo
          pango
          librsvg

    - name: Configure Meson build
      env:
        MXE_ROOT: /usr/lib/mxe/usr/x86_64-w64-mingw32.static
        PATH: $MXE_ROOT/bin:$PATH
        PKG_CONFIG_PATH: $MXE_ROOT/lib/pkgconfig
      run: |
        mkdir -p build
        cd build
        meson setup . \
          --cross-file $MXE_ROOT/share/mxe/toolchain.mxe \
          --prefix $PWD/install \
          --default-library=static \
          -Dbuildtype=release \
          -Db_lto=true \
          -Dintrospection=disabled \
          ..

    - name: Build and install
      run: |
        cd build
        ninja
        ninja install

    - name: Upload rsvg-convert.exe
      uses: actions/upload-artifact@v3
      with:
        name: rsvg-convert-windows
        path: build/install/bin/rsvg-convert.exe
