name: Build rsvg-convert on Windows (MSYS2)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      RSVG_TAG: 2.60.0   # 要编译的 librsvg 版本

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone librsvg source
        shell: pwsh
        run: |
          git clone --depth 1 --branch $env:RSVG_TAG `
            https://gitlab.gnome.org/GNOME/librsvg.git librsvg

      - name: Setup MSYS2 and install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            git
            p7zip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-rust
            mingw-w64-x86_64-cargo-c
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-gcc-libs
            mingw-w64-x86_64-gi-docgen
            mingw-w64-x86_64-gobject-introspection
            mingw-w64-x86_64-python-docutils
            mingw-w64-x86_64-vala

      - name: Build static rsvg-convert
        shell: msys2 {0}
        run: |
          cd librsvg
          mkdir build-static && cd build-static

          # 使用绝对路径作为 prefix，并使用静态库
          meson setup build \
            --prefix $(pwd)/install \
            --default-library static \
            --buildtype release \
            -Db_lto=false \
            -Dintrospection=disabled \
            -Dpixbuf-loader=disabled \
            -Dtests=false \
            -Dc_args="-static" \
            -Dcpp_args="-static" \
            -Dc_link_args="-static -static-libgcc" \
            -Dcpp_link_args="-static -static-libgcc -static-libstdc++" \
            ..

          ninja -C build
          ninja -C build install

          # 测试可执行文件
          cd install/bin
          ./rsvg-convert --version

      - name: Upload static rsvg-convert.exe
        uses: actions/upload-artifact@v4
        with:
          name: rsvg-convert-windows-static-${{ env.RSVG_TAG }}
          path: librsvg/build-static/install/bin/rsvg-convert.exe
