name: Cross-compile rsvg-convert for Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest
    env:
      # 目标 MXE 三方工具链
      MXE_TARGET: x86_64-w64-mingw32.static
      # 要编译的 librsvg 版本
      RSVG_TAG: 2.60.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone librsvg source
        run: |
          git clone https://gitlab.gnome.org/GNOME/librsvg.git
          cd librsvg
          git checkout "${RSVG_TAG}"

      - name: Setup MXE APT repository
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common lsb-release
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 86B72ED9
          sudo add-apt-repository "deb [arch=amd64] https://pkg.mxe.cc/repos/apt $(lsb_release -sc) main"
          sudo apt-get update

      - name: Install MXE cross compiler & static libraries
        run: |
          sudo apt-get install -y \
            mxe-$MXE_TARGET-cc \
            mxe-$MXE_TARGET-glib \
            mxe-$MXE_TARGET-libxml2 \
            mxe-$MXE_TARGET-cairo \
            mxe-$MXE_TARGET-pango \
            mxe-$MXE_TARGET-librsvg

      - name: Configure and build with Meson
        run: |
          # 在 shell 里计算前缀路径
          MXE_PREFIX=/usr/lib/mxe/usr/$MXE_TARGET
          export PATH=$MXE_PREFIX/bin:$PATH
          export PKG_CONFIG_PATH=$MXE_PREFIX/lib/pkgconfig

          cd librsvg
          mkdir -p build && cd build

          # 静态链接所有依赖，并开启 LTO 优化
          meson setup . \
            --cross-file $MXE_PREFIX/share/mxe/toolchain.mxe \
            --prefix install \
            --default-library=static \
            -Dbuildtype=release \
            -Db_lto=true \
            -Dintrospection=disabled \
            ..

          ninja
          ninja install

      - name: Upload rsvg-convert.exe
        uses: actions/upload-artifact@v4
        with:
          name: rsvg-convert-windows
          path: librsvg/build/install/bin/rsvg-convert.exe
