name: Cross-compile rsvg-convert for Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest
    env:
      # 目标 MXE 三方工具链
      MXE_TARGET: x86_64-w64-mingw32.static
      # 要编译的 librsvg 版本
      RSVG_TAG: 2.60.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone librsvg source
        run: |
          git clone https://gitlab.gnome.org/GNOME/librsvg.git
          cd librsvg
          git checkout "${RSVG_TAG}"

      - name: Setup MXE APT repository
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common lsb-release
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 86B72ED9
          echo "deb [arch=amd64] https://pkg.mxe.cc/repos/apt focal main" | sudo tee /etc/apt/sources.list.d/mxe.list
          sudo apt-get update

      - name: Install build tools (Meson, Ninja, pkg-config)
        run: |
          sudo apt-get install -y meson ninja-build pkg-config
        shell: bash

      - name: Install MXE cross compiler & static libraries
        run: |
          sudo apt-get install -y \
            mxe-x86-64-w64-mingw32.static-cc \
            mxe-x86-64-w64-mingw32.static-glib \
            mxe-x86-64-w64-mingw32.static-libxml2 \
            mxe-x86-64-w64-mingw32.static-cairo \
            mxe-x86-64-w64-mingw32.static-pango \
            mxe-x86-64-w64-mingw32.static-librsvg
        shell: bash

      - name: Configure and build with Meson
        run: |
          # 在 shell 里计算前缀路径
          MXE_PREFIX=/usr/lib/mxe/usr/$MXE_TARGET
          export PATH=$MXE_PREFIX/bin:$PATH
          export PKG_CONFIG_PATH=$MXE_PREFIX/lib/pkgconfig

          cd librsvg
          mkdir -p build && cd build

          # 生成 Meson cross-file，指定 MXE 提供的交叉编译工具
          cat > mxe_cross_file.txt <<EOF
          [binaries]
          c = '$MXE_PREFIX/bin/x86_64-w64-mingw32.static-gcc'
          cpp = '$MXE_PREFIX/bin/x86_64-w64-mingw32.static-g++'
          ar = '$MXE_PREFIX/bin/x86_64-w64-mingw32.static-ar'
          strip = '$MXE_PREFIX/bin/x86_64-w64-mingw32.static-strip'
          pkgconfig = '$MXE_PREFIX/bin/x86_64-w64-mingw32.static-pkg-config'

          [properties]
          needs_exe_wrapper = true

          [host_machine]
          system = 'windows'
          cpu_family = 'x86_64'
          cpu = 'x86_64'
          endian = 'little'
          EOF

          # 静态链接所有依赖，并开启 LTO 优化
          meson setup \
            --cross-file mxe_cross_file.txt \
            --prefix install \
            --default-library=static \
            -Dbuildtype=release \
            -Db_lto=true \
            -Dintrospection=disabled \
            ..

          ninja
          ninja install

      - name: Upload rsvg-convert.exe
        uses: actions/upload-artifact@v4
        with:
          name: rsvg-convert-windows
          path: librsvg/build/install/bin/rsvg-convert.exe
